// =========================================================================
// 실습예제 — 모듈별 10개씩(총 70개). /examples 페이지에서 사용.
// 각 예제: { no, title, task(실습 지시), prompt(복붙용 예시), tool }
// 키는 모듈 id(m1~m7).
// =========================================================================

export const practiceExamples = {
  // ---- M1. AI 기반 업무효율화의 이해 -------------------------------------
  m1: [
    { no: 1, title: '반복업무 진단표', tool: 'ChatGPT',
      task: '내 홍보 업무를 반복성·자동화 적합도로 분류한다.',
      prompt: '내 홍보 업무 목록을 줄게. (1)반복성 (2)자동화 적합도 (3)추천 도구를 1~5점 표로 정리하고 자동화 우선순위를 제안해줘.\n[업무] 인스타 주3회, 월간 보도자료, 행사 카드뉴스' },
    { no: 2, title: 'AI 도구 지도', tool: 'ChatGPT',
      task: '콘텐츠·이미지·페이지 단계별 대표 도구를 비교한다.',
      prompt: '홍보 실무용 AI 도구를 글·이미지·페이지 3단계로 나눠, 각 단계 대표 도구 3개와 무료 여부·강점을 표로 정리해줘.' },
    { no: 3, title: '업무 시간 절감 추정', tool: 'ChatGPT',
      task: '업무별 AI 도입 전후 소요시간을 추정한다.',
      prompt: '아래 업무들의 현재 소요시간을 알려주면, AI 도입 후 예상시간과 월간 절감시간을 표로 계산해줘.' },
    { no: 4, title: '자동화 1순위 선정', tool: 'ChatGPT',
      task: 'ROI 기준으로 자동화 우선순위를 매긴다.',
      prompt: '다음 업무들을 (절감시간×빈도) − (학습·검수비용) 관점에서 자동화 ROI 순위로 정렬하고 이유를 적어줘.' },
    { no: 5, title: '업무 절차 문서화', tool: 'ChatGPT',
      task: '반복업무를 입력→처리→출력 단계로 쪼갠다.',
      prompt: '아래 반복업무를 "입력 → 처리 → 출력" 단계로 분해하고, 각 단계에서 AI가 도울 수 있는 지점을 표시해줘.\n업무: 매주 신제품 인스타 게시글 작성' },
    { no: 6, title: 'AI/사람 역할 분담', tool: 'ChatGPT',
      task: '단계별로 AI와 사람의 역할을 나눈다.',
      prompt: '위 업무 절차의 각 단계를 "AI가 하는 일 / 사람이 검수할 점"으로 나눠 표로 만들어줘.' },
    { no: 7, title: '도입 리스크 체크리스트', tool: 'Claude',
      task: '환각·저작권·톤 리스크를 점검한다.',
      prompt: '중소기업이 생성형 AI로 홍보물을 만들 때 점검해야 할 리스크(환각·저작권·초상권·톤)를 체크리스트 8개로 만들어줘.' },
    { no: 8, title: '주간 홍보 캘린더', tool: 'ChatGPT',
      task: '반복 홍보 일정을 캘린더로 정리한다.',
      prompt: '주간 홍보 업무를 요일별 캘린더로 정리해줘. 각 항목에 채널·소요시간·자동화 가능 여부를 표시.' },
    { no: 9, title: 'AI 활용 시나리오', tool: 'ChatGPT',
      task: '우리 회사 맞춤 적용 시나리오를 만든다.',
      prompt: '우리 회사 정보를 줄게. 가장 효과 큰 AI 홍보 자동화 시나리오 1개를 단계별로 설계하고 기대 효과를 적어줘.' },
    { no: 10, title: '효율화 한 장 보고', tool: 'Claude',
      task: '상사 보고용 1장 요약을 만든다.',
      prompt: '아래 진단 결과를 경영진 보고용 한 장으로 요약해줘. 현황·문제·AI 도입안·기대 절감시간 순으로.' },
  ],

  // ---- M2. AI 기반 홍보 기획 실무 ----------------------------------------
  m2: [
    { no: 1, title: '타깃 페르소나 3종', tool: 'ChatGPT',
      task: '제품의 타깃을 3개 페르소나로 구체화한다.',
      prompt: '아래 제품의 타깃 고객을 서로 다른 3개 페르소나로 만들어줘. 각 페르소나에 연령·역할·고민·구매동기를 포함.\n제품: 무알콜 수제 맥주' },
    { no: 2, title: '메시지 하우스 도출', tool: 'Claude',
      task: '핵심 메시지 1 + 근거 3을 세운다.',
      prompt: '아래 정보로 핵심 메시지 1문장 + 뒷받침 근거 3개(메시지 하우스)를 만들어줘.\n제품·타깃·차별점: ...' },
    { no: 3, title: '가치 제안 한 문장', tool: 'ChatGPT',
      task: '"누구에게/어떤 문제/어떻게" 한 문장을 만든다.',
      prompt: '아래 제품의 가치 제안을 "누구에게 / 어떤 문제를 / 어떻게 해결"하는 한 문장으로 3가지 버전 써줘.' },
    { no: 4, title: '경쟁사 메시지 비교', tool: 'Claude',
      task: '경쟁사와 우리의 메시지 차별점을 찾는다.',
      prompt: '경쟁사 3곳의 홍보 메시지를 줄게. 공통점·차별점을 분석하고 우리가 가져갈 빈자리(포지셔닝)를 제안해줘.' },
    { no: 5, title: '핵심 키워드 추출', tool: 'ChatGPT',
      task: '콘텐츠·검색용 핵심 키워드를 뽑는다.',
      prompt: '아래 제품 소개를 보고 SNS·검색에 쓸 핵심 키워드 15개를 대형·중형·롱테일로 분류해줘.' },
    { no: 6, title: 'R-C-T-F 프롬프트', tool: 'ChatGPT',
      task: '역할·맥락·작업·형식 구조로 프롬프트를 쓴다.',
      prompt: '[역할] 15년차 카피라이터 [맥락] 30대 직장인, 위트있는 톤 [작업] 인스타 헤드라인 5개 [형식] 25자 이내, 텍스트만\n제품: 무알콜 수제 맥주' },
    { no: 7, title: 'few-shot 예시 세트', tool: 'ChatGPT',
      task: '톤 고정용 예시 2~3개를 만든다.',
      prompt: '우리 브랜드 톤을 보여주는 카피 예시 3개를 만들어줘. 이후 이 예시 톤을 그대로 모방해서 새 카피를 쓸 거야.' },
    { no: 8, title: '톤앤매너 가이드', tool: 'Claude',
      task: '말투·금지표현을 1줄 가이드로 고정한다.',
      prompt: '우리 브랜드의 톤앤매너 가이드를 1줄로 정의해줘(말투·존댓말 여부·금지 표현 포함). 프롬프트에 매번 붙일 거야.' },
    { no: 9, title: '막연 vs 구체 비교', tool: 'ChatGPT',
      task: '같은 요청을 두 방식으로 생성해 비교한다.',
      prompt: '"카피 써줘"(막연)와 R-C-T-F+예시(구체) 두 방식으로 각각 카피를 만들고, 결과 차이를 표로 비교해줘.' },
    { no: 10, title: '캠페인 한 줄 컨셉', tool: 'Claude',
      task: '캠페인 전체를 관통하는 한 줄을 만든다.',
      prompt: '메시지 하우스를 줄게. 이걸 관통하는 캠페인 슬로건(한 줄)을 톤별로 5개 제안하고 추천 1개를 골라줘.' },
  ],

  // ---- M3. AI 기반 콘텐츠 작성 실습 --------------------------------------
  m3: [
    { no: 1, title: '제품 소개문(PAS)', tool: 'ChatGPT',
      task: '문제→공감→해결 구조로 소개문을 쓴다.',
      prompt: 'PAS(문제→공감→해결) 구조로 280자 소개문을 써줘. 특징은 고객 이득으로 바꿔서.\n핵심 메시지·제품 정보: ...' },
    { no: 2, title: '인스타 캡션 + 해시태그', tool: 'ChatGPT',
      task: '캡션 1개와 해시태그 10개를 만든다.',
      prompt: '인스타 캡션 120자 이내 + 해시태그 10개(대형3·중형4·롱테일3)를 만들어줘. 톤은 따뜻·위트.' },
    { no: 3, title: '블로그 도입부(SEO)', tool: 'Claude',
      task: '검색 키워드를 넣은 도입 3문단을 쓴다.',
      prompt: '검색 키워드 "무알콜 맥주"를 자연스럽게 포함한 블로그 도입부 3문단을 써줘. 독자의 고민으로 시작.' },
    { no: 4, title: '보도자료 초안', tool: 'Claude',
      task: '제목·리드·본문·인용 구조 초안을 만든다.',
      prompt: '우리 회사 신제품 출시 소식으로 보도자료 초안을 써줘. 제목·리드·본문·인용문 자리(빈칸) 구조로.' },
    { no: 5, title: '행사 안내문', tool: 'ChatGPT',
      task: '핵심 정보를 담은 안내문을 만든다.',
      prompt: '행사 안내문을 써줘. 일시·장소·대상·신청방법·혜택을 명확히, 200자 내외, 정중한 존댓말.' },
    { no: 6, title: '카드뉴스 5장 문구', tool: 'ChatGPT',
      task: '장당 한 문장씩 5장 문구를 만든다.',
      prompt: '카드뉴스 5장 문구를 만들어줘. 장당 15자 이내 한 문장, 1장 후킹 → 5장 CTA 흐름.' },
    { no: 7, title: '짧은 광고 카피 10종', tool: 'ChatGPT',
      task: '톤이 다른 헤드라인 10개를 뽑는다.',
      prompt: '같은 제품으로 헤드라인 10개를 써줘. 감성형·정보형·도발형을 섞고 각 25자 이내.' },
    { no: 8, title: 'FAQ 5문답', tool: 'Claude',
      task: '고객이 자주 묻는 질문과 답을 만든다.',
      prompt: '이 제품에 대해 고객이 자주 물을 질문 5개와 간결한 답변을 만들어줘. 구매 망설임을 줄이는 톤으로.' },
    { no: 9, title: '뉴스레터 제목 10종', tool: 'ChatGPT',
      task: '열어보고 싶은 메일 제목을 만든다.',
      prompt: '오픈율 높은 뉴스레터 제목 10개를 만들어줘. 30자 이내, 과장 금지, 호기심·이득 중심.' },
    { no: 10, title: '후기 요청 메시지', tool: 'ChatGPT',
      task: '고객에게 보낼 후기 요청 문구를 만든다.',
      prompt: '구매 고객에게 보낼 후기 요청 메시지를 만들어줘. 부담 없이, 1분 안에 답할 수 있게, 정중한 톤.' },
  ],

  // ---- M4. AI 기반 시각자료 제작 -----------------------------------------
  m4: [
    { no: 1, title: '홍보 배너 배경', tool: 'ImageFX',
      task: '텍스트 여백을 둔 배너 배경을 만든다.',
      prompt: 'minimal product banner background, soft studio side-light, warm amber + deep navy, clean left negative space for text, 16:9 --no text, logo, real people, watermark' },
    { no: 2, title: '유튜브 썸네일', tool: 'ImageFX',
      task: '시선을 끄는 16:9 썸네일을 만든다.',
      prompt: 'eye-catching youtube thumbnail background, high contrast, single focal subject, bold color block on one side for title, 16:9 --no text, faces, watermark' },
    { no: 3, title: '카드뉴스 배경 세트', tool: 'ImageFX',
      task: '동일 톤 배경 3장을 만든다.',
      prompt: 'flat minimal background, warm amber + navy, soft grain, top margin for one-line title, 1:1, make 3 variations with identical mood --no text, busy pattern' },
    { no: 4, title: '제품 무드컷', tool: 'DALL·E',
      task: '브랜드 분위기를 담은 무드 이미지를 만든다.',
      prompt: 'moody product photography vibe for a craft beverage, warm light, shallow depth, premium minimal, navy backdrop --no text, logo, hands' },
    { no: 5, title: '인스타 1:1 그래픽', tool: 'Canva AI',
      task: '피드용 정사각 그래픽을 만든다.',
      prompt: '1:1 instagram graphic background, brand colors amber+navy, simple geometric accent, lots of clear space for a quote --no text' },
    { no: 6, title: '이벤트 포스터 배경', tool: 'ImageFX',
      task: '행사 포스터용 세로 배경을 만든다.',
      prompt: 'event poster background, vertical 4:5, festive but minimal, warm gradient, space at center for title and date --no text, crowd' },
    { no: 7, title: '배경 제거·확장', tool: 'Canva AI',
      task: '생성 이미지를 규격에 맞게 후처리한다.',
      prompt: '(편집) 제품 컷의 배경을 제거하고, 인스타 스토리(9:16)에 맞게 배경을 자연스럽게 확장(outpaint)해줘.' },
    { no: 8, title: '브랜드 컬러 보정', tool: 'Canva AI',
      task: '이미지를 브랜드 팔레트로 통일한다.',
      prompt: '(편집) 이 카드뉴스 3장의 색감을 amber+navy 팔레트로 통일하고 밝기를 맞춰줘.' },
    { no: 9, title: '아이콘 스타일 세트', tool: 'ImageFX',
      task: '일관된 스타일의 아이콘을 만든다.',
      prompt: 'set of 4 simple line icons, consistent stroke, navy on transparent, topics: beer, leaf, clock, heart --no text, color fill' },
    { no: 10, title: '시즌 프로모션 비주얼', tool: 'DALL·E',
      task: '시즌 캠페인용 비주얼을 만든다.',
      prompt: 'seasonal promotion key visual, summer mood, refreshing, amber+navy with light highlights, space for headline, 16:9 --no text, logo' },
  ],

  // ---- M5. AI 기반 UI 시안 제작 (Google Stitch) --------------------------
  m5: [
    { no: 1, title: '랜딩페이지 브리프', tool: 'Google Stitch',
      task: '목적·섹션·톤을 담은 브리프로 시안을 만든다.',
      prompt: 'Create a landing page for a craft non-alcoholic beer. Goal: pre-order. Tone: warm premium minimal. Sections: hero+CTA, 3 features, quotes, FAQ, final CTA. Mobile-first.' },
    { no: 2, title: '이벤트 페이지 시안', tool: 'Google Stitch',
      task: '단일 이벤트용 원페이지 시안을 만든다.',
      prompt: 'Design an event landing page. Single goal: register. Include hero with date/place, agenda, speakers, register form, FAQ.' },
    { no: 3, title: '제품 상세 시안', tool: 'Google Stitch',
      task: '상세페이지 구조 시안을 만든다.',
      prompt: 'Create a product detail page: hero image + price + CTA, benefits, specs, reviews, related, sticky buy bar. Clean and trustworthy.' },
    { no: 4, title: '히어로 섹션 변형', tool: 'Google Stitch',
      task: '히어로를 3가지로 변형한다.',
      prompt: 'Give me 3 hero section variations for the same landing page: A) image-left B) centered C) full-bleed background. Keep one CTA.' },
    { no: 5, title: '모바일 우선 레이아웃', tool: 'Google Stitch',
      task: '모바일 기준으로 화면을 재구성한다.',
      prompt: 'Rework this page mobile-first: large tap targets, sticky CTA bar, one column, shorten sections.' },
    { no: 6, title: '가격표 섹션', tool: 'Google Stitch',
      task: '플랜 비교 가격표를 만든다.',
      prompt: 'Add a pricing section with 2 plans, highlight the recommended one, each with 4 perks and a CTA button.' },
    { no: 7, title: '후기 섹션', tool: 'Google Stitch',
      task: '신뢰를 주는 후기 섹션을 만든다.',
      prompt: 'Add a social proof section: 3 customer quotes with name/role, a row of partner logos, and a rating number.' },
    { no: 8, title: 'FAQ 아코디언', tool: 'Google Stitch',
      task: '자주 묻는 질문 섹션을 만든다.',
      prompt: 'Add an FAQ accordion with 5 question-answer pairs about shipping, taste, calories, returns, gifting.' },
    { no: 9, title: '신청 폼 섹션', tool: 'Google Stitch',
      task: '전환용 신청/문의 폼을 만든다.',
      prompt: 'Add a sign-up form section: name, email, optional message, a clear benefit line, and a primary submit button.' },
    { no: 10, title: '시안 부분 수정 지시', tool: 'Google Stitch',
      task: '반복 수정으로 시안을 다듬는다.',
      prompt: 'Refine: move primary CTA into the hero, add a sticky top bar with CTA, reduce to hero/benefits/proof/CTA, keep single goal.' },
  ],

  // ---- M6. AI 기반 페이지 구성 실무 --------------------------------------
  m6: [
    { no: 1, title: '히어로 카피', tool: 'ChatGPT',
      task: '헤드라인+보조문구를 만든다.',
      prompt: '랜딩 히어로용 헤드라인 1줄(20자 내) + 보조문구 1줄을 3세트 써줘. 핵심 메시지: 부담 없이 즐기는 진짜 맥주맛.' },
    { no: 2, title: '특징 3개 이득형 카피', tool: 'ChatGPT',
      task: '스펙을 이득으로 번역한다.',
      prompt: '아래 제품 특징 3개를 각각 [소제목 + 이득 한 줄]로 바꿔줘. 스펙 나열 금지.' },
    { no: 3, title: 'CTA 문구 A/B 3종', tool: 'ChatGPT',
      task: '이득형 버튼 문구를 만든다.',
      prompt: '랜딩 CTA 버튼 문구 3종을 만들어줘. 이득형 동사로, "지금 ~받기" 형태, 각 12자 이내.' },
    { no: 4, title: '사회적 증거 문구', tool: 'Claude',
      task: '후기·숫자로 신뢰 문구를 만든다.',
      prompt: '신뢰를 주는 사회적 증거 섹션 문구를 만들어줘. "누적 판매 N개", 후기 3개(가상 표시), 한 줄 헤드라인 포함.' },
    { no: 5, title: 'AIDA 흐름 재배열', tool: 'Claude',
      task: '섹션 순서를 전환 흐름으로 바꾼다.',
      prompt: '현재 섹션 순서를 AIDA(주의→관심→욕구→행동) 관점에서 재배열하고 이유를 적어줘.\n현재: 특징→히어로→FAQ→후기→CTA' },
    { no: 6, title: '섹션 우선순위 정리', tool: 'ChatGPT',
      task: '핵심만 남기고 군더더기를 덜어낸다.',
      prompt: '이 랜딩의 섹션 목록을 줄게. "한 페이지 한 목표" 원칙으로 꼭 필요한 섹션만 남기고 순서를 정리해줘.' },
    { no: 7, title: '모바일 흐름 점검', tool: 'ChatGPT',
      task: '모바일에서 메시지 흐름을 점검한다.',
      prompt: '이 페이지가 모바일에서 첫 화면에 핵심 메시지+CTA가 보이는지 점검하고 개선점 3개를 제안해줘.' },
    { no: 8, title: '신뢰 요소 배치', tool: 'Claude',
      task: '보증·후기·로고 배치를 제안한다.',
      prompt: '구매 망설임을 줄일 신뢰 요소(보증·후기·로고·반품정책)를 페이지 어디에 배치할지 흐름과 함께 제안해줘.' },
    { no: 9, title: '이탈 줄이는 카피', tool: 'ChatGPT',
      task: '망설임 포인트를 해소하는 카피를 만든다.',
      prompt: '고객이 이탈하는 주요 이유 3개를 가정하고, 각 이유를 해소하는 짧은 안심 카피를 1줄씩 써줘.' },
    { no: 10, title: '마무리 CTA 강화', tool: 'ChatGPT',
      task: '페이지 끝 CTA를 강화한다.',
      prompt: '페이지 맨 아래 마무리 CTA 섹션 문구를 만들어줘. 요약 한 줄 + 이득형 버튼 + 한정·긴급 요소(과장 금지).' },
  ],

  // ---- M7. AI 기반 반복업무 자동화 ---------------------------------------
  m7: [
    { no: 1, title: '워크플로 설계', tool: 'ChatGPT',
      task: '트리거→생성→검수→발행 흐름을 설계한다.',
      prompt: '아래 반복업무를 "트리거 / AI 단계 / 사람 검수 / 발행" 표로 설계하고 단계별 도구·소요시간을 적어줘.\n업무: 매주 인스타 게시글+카드뉴스' },
    { no: 2, title: '프롬프트 라이브러리', tool: '노션',
      task: '재사용 프롬프트를 용도별로 정리한다.',
      prompt: '오늘 쓴 프롬프트들을 용도별(카피·이미지·페이지) 라이브러리로 정리해줘. 각 항목에 입력 변수와 사용 팁을 표기.' },
    { no: 3, title: '콘텐츠 리퍼포징 계획', tool: 'ChatGPT',
      task: '하나의 콘텐츠를 여러 채널로 재활용한다.',
      prompt: '블로그 글 1편을 인스타·카드뉴스·뉴스레터·릴스로 재가공하는 리퍼포징 계획을 표로 만들어줘.' },
    { no: 4, title: '주간 발행 캘린더', tool: 'ChatGPT',
      task: '반복 발행 일정을 템플릿화한다.',
      prompt: '주간 콘텐츠 발행 캘린더 템플릿을 만들어줘. 요일·채널·콘텐츠유형·담당(AI/사람)·상태 칼럼 포함.' },
    { no: 5, title: '체크리스트 템플릿', tool: '노션',
      task: '발행 전 검수 체크리스트를 만든다.',
      prompt: '콘텐츠 발행 전 검수 체크리스트를 만들어줘(사실확인·톤·오타·저작권·CTA·규격). 8~10개 항목.' },
    { no: 6, title: 'Make/Zapier 시나리오', tool: 'Make',
      task: '단계를 자동 연결하는 시나리오를 그린다.',
      prompt: '"새 블로그 글 발행 → 요약 생성 → SNS 초안 작성 → 검수 알림"을 Make 시나리오로 단계(트리거-액션) 설계해줘.' },
    { no: 7, title: '검수 게이트 정의', tool: 'ChatGPT',
      task: '사람이 반드시 확인할 지점을 정한다.',
      prompt: '내 자동화 워크플로에서 사람이 반드시 검수해야 할 지점과 그 이유, 통과 기준을 정리해줘.' },
    { no: 8, title: '결과물 패키지 정리', tool: '구글 문서',
      task: '오늘 산출물을 한 문서로 묶는다.',
      prompt: '오늘 만든 결과물(메시지·소개문·카드뉴스·시안·페이지)을 한 문서로 정리하는 목차와 양식을 만들어줘.' },
    { no: 9, title: '발표 스크립트', tool: 'Claude',
      task: '2분 발표용 스크립트를 만든다.',
      prompt: '오늘 결과물 목록을 줄게. 2분 발표용 스크립트(만든 것·배운 점·적용 계획)를 만들어줘.' },
    { no: 10, title: '30일 적용 계획', tool: 'ChatGPT',
      task: '현업 적용 30일 실행 계획을 만든다.',
      prompt: '워크숍 내용을 현업에 적용할 30일 계획을 주차별로 만들어줘. 매주 실행 1가지를 요일·시간까지 구체화.' },
  ],
}
